### ISSUE TITLE
Apex installation failed

### ISSUE THREAD

**Issue by Astralex98** [amazon-science/earth-forecasting-transformer#53]
Hi!

Thanks for your work! I am trying to reproduce the result on my host. All was good before installing Apex, but installing Apex crushes with error. I see that issue with Apex had been created, but my mistake with Apex is different. First of all, I tried to install Apex in a standard way:

python3 -m pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" pytorch-extension git+https://github.com/NVIDIA/apex.git

But I have following mistake:
![My_error_1](https://github.com/amazon-science/earth-forecasting-transformer/assets/49883300/b3b80293-af4f-410e-b015-02b35492dc58)

I tried to install “packaging” in my environment but it has been already installed:
![Packagin_installed](https://github.com/amazon-science/earth-forecasting-transformer/assets/49883300/249f6bad-3507-401d-ae82-40edcb552908)

So I don’t know what is the possible problem. After that I moved on to your Colab “inference tutorial” and tried to reproduce result here but I have following error:
![Colab_error](https://github.com/amazon-science/earth-forecasting-transformer/assets/49883300/4b9b090f-808a-458b-bf81-77c9537eab53)

Please, help me find out the problem.

Thanks in advance!

**Comment by gaozhihan** [comment]
Thanks for your question. NVIDIA Apex has had several updates since the release of this repo. The [installation instructions](https://github.com/amazon-science/earth-forecasting-transformer/blob/0303b37178940dd27acbcb619ffd9c381731a224/README.md?plain=1#L64-L65) for Apex in this repo is outdated. You may want to refer to the [latest official instructions](https://github.com/NVIDIA/apex/blob/7b2e71b0d4013f8e2f9f1c8dd21980ff1d76f1b6/README.md?plain=1#L105) to install Apex. It works correctly according to my tests.

**Comment by Astralex98** [comment]
Thanks! Now the Apex installation was successful! Thanks for quick response!
